### ISSUE TITLE
(internal) intermittent exceptions

### ISSUE THREAD

**Issue by vidiecan** [WillemElbers/unity-idm#1]
```
java.lang.NullPointerException
unity-idm_1      |  at pl.edu.icm.unity.engine.authz.AuthorizationManagerImpl.isSelf(AuthorizationManagerImpl.java:260)
unity-idm_1      |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unity-idm_1      |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unity-idm_1      |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unity-idm_1      |  at java.lang.reflect.Method.invoke(Method.java:498)
unity-idm_1      |  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
unity-idm_1      |  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
unity-idm_1      |  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
unity-idm_1      |  at com.sun.proxy.$Proxy31.isSelf(Unknown Source)
unity-idm_1      |  at pl.edu.icm.unity.engine.AttributesManagementImpl.getAllAttributesInternal(AttributesManagementImpl.java:611)
unity-idm_1      |  at pl.edu.icm.unity.engine.AttributesManagementImpl.getAttributes(AttributesManagementImpl.java:561)
unity-idm_1      |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
unity-idm_1      |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
unity-idm_1      |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unity-idm_1      |  at java.lang.reflect.Method.invoke(Method.java:498)
unity-idm_1      |  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
unity-idm_1      |  at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:43)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
unity-idm_1      |  at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
unity-idm_1      |  at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
unity-idm_1      |  at pl.edu.icm.unity.engine.transactions.TransactionalAspect.retryIfNeeded(TransactionalAspect.java:65)
unity-idm_1      |  at pl.edu.icm.unity.engine.transactions.TransactionalAspect.retryIfNeeded4Method(TransactionalAspect.java:54)
unity-idm_1      |  at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
unity-idm_1      |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
unity-idm_1      |  at java.lang.reflect.Method.invoke(Method.java:498)
unity-idm_1      |  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
unity-idm_1      |  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
unity-idm_1      |  at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
unity-idm_1      |  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
unity-idm_1      |  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
unity-idm_1      |  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
unity-idm_1      |  at com.sun.proxy.$Proxy42.getAttributes(Unknown Source)
unity-idm_1      |  at pl.edu.icm.unity.ldap.endpoint.LdapApacheDSInterceptor.getUser(LdapApacheDSInterceptor.java:507)
unity-idm_1      |  at pl.edu.icm.unity.ldap.endpoint.LdapApacheDSInterceptor.search(LdapApacheDSInterceptor.java:198)
unity-idm_1      |  at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:596)
unity-idm_1      |  at org.apache.directory.server.core.normalization.NormalizationInterceptor.search(NormalizationInterceptor.java:304)
unity-idm_1      |  at org.apache.directory.server.core.DefaultOperationManager.search(DefaultOperationManager.java:1342)
unity-idm_1      |  at org.apache.directory.server.core.shared.DefaultCoreSession.search(DefaultCoreSession.java:1122)
unity-idm_1      |  at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.doSimpleSearch(SearchRequestHandler.java:810)
unity-idm_1      |  at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.handleIgnoringReferrals(SearchRequestHandler.java:1164)
unity-idm_1      |  at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.handleWithReferrals(SearchRequestHandler.java:1258)
unity-idm_1      |  at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.handle(SearchRequestHandler.java:212)
unity-idm_1      |  at org.apache.directory.server.ldap.handlers.request.SearchRequestHandler.handle(SearchRequestHandler.java:92)
unity-idm_1      |  at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:207)
unity-idm_1      |  at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:56)
unity-idm_1      |  at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:221)
```

**Comment by vidiecan** [comment]
the problem is that messages in LDAP are processed on one thread but auth. is stored per connection in TLS.
